# Generated by Django 5.0.2 on 2024-03-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('publisher', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(blank=True)),
                ('tel', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
